import { z } from "zod";

export const accuracyCheckCreateSchema = z.object({
    generalDataId: z.string(),
    unit: z.number(),
    balancerAirPsr: z.number(),
    prlAdj_0A: z.number(),
    prlAdj_0B: z.number(),
    prlAdj_0C: z.number(),
    prlAdj_0D: z.number(),
    prlAdj_180A: z.number(),
    prlAdj_180B: z.number(),
    prlAdj_180C: z.number(),
    prlAdj_180D: z.number(),
    prlActVlv: z.number(),
    prlAllowance: z.number(),
    prlJudgement: z.string(),
    gibAdj_0A: z.number(),
    gibAdj_0B: z.number(),
    gibAdj_0C: z.number(),
    gibAdj_0D: z.number(),
    gibAdj_180A: z.number(),
    gibAdj_180B: z.number(),
    gibAdj_180C: z.number(),
    gibAdj_180D: z.number(),
    gibActVlv: z.number(),
    gibAllowance: z.number(),
    gibJudgement: z.string(),
    ppdcltSlideStroke: z.number(),
    ppdcltAdjLrA: z.number(),
    ppdcltAdjLrB: z.number(),
    ppdcltAdjLrC: z.number(),
    ppdcltAdjLrD: z.number(),
    ppdcltAdjFrA: z.number(),
    ppdcltAdjFrB: z.number(),
    ppdcltAdjFrC: z.number(),
    ppdcltAdjFrD: z.number(),
    ppdcltLrActValue: z.number(),
    ppdcltLrAllowance: z.number(),
    ppdcltLrJudgement: z.string(),
    ppdcltFrActValue: z.number(),
    ppdcltFrAllowance: z.number(),
    ppdcltFrJudgement: z.string(),
    ttlClrActValue: z.number(),
    ttlClrActValve: z.number(),
    ttlClrAllowance: z.number(),
    ttlClrJudgement: z.string(),
});
