image: ubuntu
pages:
  stage: deploy
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  before_script:
    - export SSH_USERNAME=$SSH_USERNAME
    - export SSH_HOST=$SSH_HOST
    - export SSH_PORT=$SSH_PORT
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash

  script:
    - ssh -i "admin.pem" $SSH_USERNAME@$SSH_HOST:$SSH_PORT "cd ~/apps/nig-backend && git checkout main && git pull origin main && exit"
  only:
    - main