image: alpine
deploy_to_dev:
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  before_script:
    - 'which ssh-agent || ( apk add --no-cache openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts || echo "$SSH_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apk add curl bash

  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - chmod 400 ./admin.pem || echo "Gagal Edit Permission admin.pem"
    - ssh -i "./admin.pem" $SSH_USERNAME@$SSH_HOST "\
        cd ~/apps/nig-backend && \
        git checkout main && \
        git pull origin main && \
        exit"
  only:
    - main