import { AccuracyCheck } from "@/domain/models/accuracy-check";
import { AccuracyCheckRepository } from "@/domain/service/accuracy-check-repository";
import { AccuracyCheck as AccuracyCheckDB } from "@/infrastructure/database/models";
import { injectable } from "inversify";

@injectable()
export class AccuracyCheckSequelizeRepository implements AccuracyCheckRepository {
    async store(accuracyCheck: AccuracyCheck): Promise<AccuracyCheck> {
        const created = await AccuracyCheckDB.create({
            id: accuracyCheck.id,
            general_data_id: accuracyCheck.generalDataId,
            unit: accuracyCheck.unit,
            balancer_air_psr: accuracyCheck.balancerAirPsr,
            prl_adj_0_a: accuracyCheck.prlAdj_0A,
            prl_adj_0_b: accuracyCheck.prlAdj_0B,
            prl_adj_0_c: accuracyCheck.prlAdj_0C,
            prl_adj_0_d: accuracyCheck.prlAdj_0D,
            prl_adj_180_a: accuracyCheck.prlAdj_180A,
            prl_adj_180_b: accuracyCheck.prlAdj_180B,
            prl_adj_180_c: accuracyCheck.prlAdj_180C,
            prl_adj_180_d: accuracyCheck.prlAdj_180D,
            prl_act_vlv: accuracyCheck.prlActVlv,
            prl_allowance: accuracyCheck.prlAllowance,
            prl_judgement: accuracyCheck.prlJudgement,
            gib_adj_0_a: accuracyCheck.gibAdj_0A,
            gib_adj_0_b: accuracyCheck.gibAdj_0B,
            gib_adj_0_c: accuracyCheck.gibAdj_0C,
            gib_adj_0_d: accuracyCheck.gibAdj_0D,
            gib_adj_180_a: accuracyCheck.gibAdj_180A,
            gib_adj_180_b: accuracyCheck.gibAdj_180B,
            gib_adj_180_c: accuracyCheck.gibAdj_180C,
            gib_adj_180_d: accuracyCheck.gibAdj_180D,
            gib_act_vlv: accuracyCheck.gibActVlv,
            gib_allowance: accuracyCheck.gibAllowance,
            gib_judgement: accuracyCheck.gibJudgement,
            ppdclt_slide_stroke: accuracyCheck.ppdcltSlideStroke,
            ppdclt_adj_lr_a: accuracyCheck.ppdcltAdjLrA,
            ppdclt_adj_lr_b: accuracyCheck.ppdcltAdjLrB,
            ppdclt_adj_lr_c: accuracyCheck.ppdcltAdjLrC,
            ppdclt_adj_lr_d: accuracyCheck.ppdcltAdjLrD,
            ppdclt_adj_fr_a: accuracyCheck.ppdcltAdjFrA,
            ppdclt_adj_fr_b: accuracyCheck.ppdcltAdjFrB,
            ppdclt_adj_fr_c: accuracyCheck.ppdcltAdjFrC,
            ppdclt_adj_fr_d: accuracyCheck.ppdcltAdjFrD,
            ppdclt_lr_act_value: accuracyCheck.ppdcltLrActValue,
            ppdclt_lr_allowance: accuracyCheck.ppdcltLrAllowance,
            ppdclt_lr_judgement: accuracyCheck.ppdcltLrJudgement,
            ppdclt_fr_act_value: accuracyCheck.ppdcltFrActValue,
            ppdclt_fr_allowance: accuracyCheck.ppdcltFrAllowance,
            ppdclt_fr_judgement: accuracyCheck.ppdcltFrJudgement,
            ttl_clr_act_value: accuracyCheck.ttlClrActValue,
            ttl_clr_act_valve: accuracyCheck.ttlClrActValve,
            ttl_clr_allowance: accuracyCheck.ttlClrAllowance,
            ttl_clr_judgement: accuracyCheck.ttlClrJudgement,
        });
        return AccuracyCheck.create({
            id: accuracyCheck.id,
            generalDataId: created.general_data_id,
            unit: created.unit,
            balancerAirPsr: created.balancer_air_psr,
            prlAdj_0A: created.prl_adj_0_a,
            prlAdj_0B: created.prl_adj_0_b,
            prlAdj_0C: created.prl_adj_0_c,
            prlAdj_0D: created.prl_adj_0_d,
            prlAdj_180A: created.prl_adj_180_a,
            prlAdj_180B: created.prl_adj_180_b,
            prlAdj_180C: created.prl_adj_180_c,
            prlAdj_180D: created.prl_adj_180_d,
            prlActVlv: created.prl_act_vlv,
            prlAllowance: created.prl_allowance,
            prlJudgement: created.prl_judgement,
            gibAdj_0A: created.gib_adj_0_a,
            gibAdj_0B: created.gib_adj_0_b,
            gibAdj_0C: created.gib_adj_0_c,
            gibAdj_0D: created.gib_adj_0_d,
            gibAdj_180A: created.gib_adj_180_a,
            gibAdj_180B: created.gib_adj_180_b,
            gibAdj_180C: created.gib_adj_180_c,
            gibAdj_180D: created.gib_adj_180_d,
            gibActVlv: created.gib_act_vlv,
            gibAllowance: created.gib_allowance,
            gibJudgement: created.gib_judgement,
            ppdcltSlideStroke: created.ppdclt_slide_stroke,
            ppdcltAdjLrA: created.ppdclt_adj_lr_a,
            ppdcltAdjLrB: created.ppdclt_adj_lr_b,
            ppdcltAdjLrC: created.ppdclt_adj_lr_c,
            ppdcltAdjLrD: created.ppdclt_adj_lr_d,
            ppdcltAdjFrA: created.ppdclt_adj_fr_a,
            ppdcltAdjFrB: created.ppdclt_adj_fr_b,
            ppdcltAdjFrC: created.ppdclt_adj_fr_c,
            ppdcltAdjFrD: created.ppdclt_adj_fr_d,
            ppdcltLrActValue: created.ppdclt_lr_act_value,
            ppdcltLrAllowance: created.ppdclt_lr_allowance,
            ppdcltLrJudgement: created.ppdclt_lr_judgement,
            ppdcltFrActValue: created.ppdclt_fr_act_value,
            ppdcltFrAllowance: created.ppdclt_fr_allowance,
            ppdcltFrJudgement: created.ppdclt_fr_judgement,
            ttlClrActValue: created.ttl_clr_act_value,
            ttlClrActValve: created.ttl_clr_act_valve,
            ttlClrAllowance: created.ttl_clr_allowance,
            ttlClrJudgement: created.ttl_clr_judgement,
            createdAt: created.created_at,
            updatedAt: created.updated_at || undefined,
        });
    }
}
